### ISSUE TITLE
Ongemak - Indicatie bij multi-select

### ISSUE THREAD

**Issue by wernerlievens** [fietsersbond-vzw/fb_tools_mow#9]
v0.47
Selecteer meerdere ongemakken.

Geen tekst in dialoog die aangeeft hoeveel er werden geselecteerd.
(wel zo bij crossing).

**Comment by PolyglotOpenstreetmap** [comment]
This should be solved with this commit: 2f92be4cd087ba88544010807a777a93343529ee
